javascript:
  enabled: false
eslint:
  enabled: true
  config_file: .eslintrc
  ignore_file: .eslintignore
scss:
  enabled: true
  config_file: .scss-lint.yml
  ignore_file: .eslintignore
fail_on_violations: true
